name: General CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"
      - uses: actions/checkout@v2
      - name: setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install node dependencies
        run: |
          yarn install
          yarn bootstrap
      - run: yarn test:sl-nest-module
      - run: yarn build:sl-nest-module
